kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: reader
rules:
- apiGroups: [“”]
  resources: ["pods", "services", "deployments"]
  verbs: [“get”, “watch”, “list”]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: editor
rules:
- apiGroups: [“”] 
  resources: ["pods", "services", "deployments"]
  verbs: ["get","list","watch", "create","update","patch","delete"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: admin
rules:
- apiGroups: [“”] 
  resources: ["*"]
  verbs: ["*"]
